version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
